#!/bin/sh

err=0

. "`dirname $0`/config.sh"

tmp="`mktemp`"

for file in src/*; do
  clang-format -style=file "$file" >"$tmp"
  chmod --reference="$file" "$tmp"

  git --no-pager diff --quiet -- "$file" "$tmp"
  if [ $? -eq 0 ]; then
    continue
  fi

  echo ""
  echo "====================================="
  echo "==== $file ..."
  echo "====================================="
  git --no-pager diff -- "$file" "$tmp"
  if [ $? -ne 0 ]; then
    err=1
  fi
done

rm "$tmp"
[ $err -ne 0 ] && echo "linter failed" >&2
exit $err
